apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthapp-project
  labels:
    app: healthapp-w1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: healthapp-w1
  template:
    metadata:
      labels:
        app: healthapp-w1
    spec:
      containers:
      - name: bankapp-w1-container
        image: venkt06/healthapp-w1-app:tagversion
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthapp-w1-np-service
  labels:
    app: healthapp-w1
spec:
  selector:
    app: healthapp-w1
  type: NodePort
  ports:
  - nodePort: 31233    
    port: 8082
    targetPort: 8082
